version: "3.8"

services:
  php-fpm:
    container_name: platinum-php-fpm
#    image: arm64v8/php:8.1-fpm
    build:
      context: ./.docker/php-fpm
    ports:
      - "9090:9000"
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  nginx:
    container_name: platinum-nginx
    image: arm64v8/nginx
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - internal

networks:
  internal:
    driver: bridge
